import 'dart:convert';

// Generated by https://quicktype.io

class ChatRequestNotification {
  Chat chat;
  ChatRequestNotification({
    required this.chat,
  });

  Map<String, dynamic> toMap() {
    return {
      'chat': chat.toMap(),
    };
  }

  factory ChatRequestNotification.fromMap(Map<String, dynamic> map) {
    var valor = map['chat'] is String ? json.decode(map['chat']) : map['chat'];
    return ChatRequestNotification(
      chat: Chat.fromMap(valor),
    );
  }

  String toJson() => json.encode(toMap());

  factory ChatRequestNotification.fromJson(String source) =>
      ChatRequestNotification.fromMap(json.decode(source));
}

class Chat {
  String requestId;
  String ofertId;
  Chat({
    required this.requestId,
    required this.ofertId,
  });

  Map<String, dynamic> toMap() {
    return {
      'requestId': requestId,
      'ofertId': ofertId,
    };
  }

  factory Chat.fromMap(Map<String, dynamic> map) {
    return Chat(
      requestId: map['requestId'] ?? '',
      ofertId: map['ofertId'] ?? '',
    );
  }

  String toJson() => json.encode(toMap());

  factory Chat.fromJson(String source) => Chat.fromMap(json.decode(source));
}
